### ISSUE TITLE
May be it would be better to make it public?

### ISSUE THREAD

**Issue by Yourun-proger** [qxf2/cars-api#16]
If you make it public, people can work it without using Docker. You should buy the domain 'api.cars-api.com' to simplify work for programmers. If you worry about payment for your domain and hosting you can add button 'Sponsor' to your repository.

**Comment by avinash010** [comment]
The domain name for[ cars-app ](https://cars-app.qxf2.com/)exists. We have not publicized it because of the traffic we receive.
